# Generated by Django 5.2.8 on 2025-11-12 22:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('icon', models.CharField(blank=True, help_text='Classe Bootstrap Icon', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='products/')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Prix de référence', max_digits=10)),
                ('amazon_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amazon_link', models.URLField(blank=True)),
                ('amazon_available', models.BooleanField(default=True)),
                ('amazon_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('amazon_reviews', models.IntegerField(default=0)),
                ('amazon_shipping', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('amazon_delivery_days', models.IntegerField(default=2, help_text='Jours de livraison')),
                ('ebay_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ebay_link', models.URLField(blank=True)),
                ('ebay_available', models.BooleanField(default=True)),
                ('ebay_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('ebay_reviews', models.IntegerField(default=0)),
                ('ebay_shipping', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('ebay_delivery_days', models.IntegerField(default=5, help_text='Jours de livraison')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('keywords', models.CharField(blank=True, max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComparisonVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('amazon', 'Amazon'), ('ebay', 'eBay')], max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='products.product')),
            ],
            options={
                'unique_together': {('product', 'ip_address')},
            },
        ),
    ]
